name: Ecosystem CI

env:
  CI: 1

on:
  workflow_call:
    inputs:
      version:
        description: "swc version to use"
        required: true
        type: string
        default: "nightly"

      suites:
        description: 'JSON array for test suites to run. Select ["_"] to run all tests'
        required: true
        type: string

      allowBreakingWasm:
        description: "Allow wasm breakage"
        required: false
        type: boolean
        default: false

      mode:
        type: string
        description: "Passing is a regular proces, and ignored is about ignored tests"

jobs:
  list-tests:
    name: "List tests"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    outputs:
      suites: ${{ steps.list-tests.outputs.suites }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - id: list-tests
        run: bun run-all.ts
        working-directory: .github/swc-ecosystem-ci
        env:
          CI_MODE: ${{ github.event.inputs.mode || 'passing' }}

  run-test-suite:
    name: Test ${{ matrix.suite }}
    needs:
      - list-tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJSON(needs.list-tests.outputs.suites) }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - run: bun run tsc
        working-directory: .github/swc-ecosystem-ci

      - id: ecosystem-ci-run
        working-directory: .github/swc-ecosystem-ci
        run: |
          bash -r
          echo $PATH
          which bun

          bun ecosystem-ci.js run-suites ${{ matrix.suite }}
        env:
          SWC_VERSION: ${{ inputs.version }}
          CI_MODE: ${{ inputs.mode }}
          ALLOW_BREAKING_WASM: ${{ inputs.allowBreakingWasm || 'false' }}

      # - if: ${{ failure() && github.event.inputs.mode == 'passing' }}
      #   name: Notify failure
      #   uses: tsickert/discord-webhook@v5.3.0
      #   with:
      #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     content: |
      #       Test for `${{ matrix.suite }}` with `${{ inputs.version }}` failed.
      #       See https://github.com/swc-project/swc-ecosystem-ci/actions/runs/${{ github.run_id }} for details.

      # - if: ${{ success() &&github.event.inputs.mode == 'ignored' }}
      #   name: Notify success
      #   uses: tsickert/discord-webhook@v5.3.0
      #   with:
      #     webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     content: |
      #       Test `${{ matrix.suite }}` is now passing
