name: "Publish crates (auto)"

env:
  CI: 1
  GIT_AUTHOR_NAME: "SWC Bot"
  GIT_AUTHOR_EMAIL: "bot@swc.rs"
  GIT_COMMITTER_NAME: "SWC Bot"
  GIT_COMMITTER_EMAIL: "bot@swc.rs"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish-cargo:
    # Run only on `chore: Publish` prefix
    name: "Publish cargo crates"
    runs-on: ubuntu-latest
    if: >-
      ${{ github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'chore: Publish') }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Install cargo-edit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit@0.12.2

      - name: Install cargo-mono
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-mono@0.4.1

      - name: Update constant of swc_core
        run: bun .github/bot/src/cargo/update-constants.ts

      - name: Publish crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo mono publish --no-verify
          (cd bindings && cargo mono publish --no-verify)
